version: "3.9"

services:

  flask:
    build: ./backend/flask_api
    ports:
      - "5001:5001"
    volumes:
      - ./backend/flask_api:/app

  django:
    build: ./backend/django_api/nahb_web
    ports:
      - "8000:8000"
    volumes:
      - ./backend/django_api/nahb_web:/app
    depends_on:
      - flask
    environment:
      STORY_API_URL: http://flask:5001
      STORY_API_KEY: super-secret-key-123
